export enum ModuleEnum {
  CATEGORY = 'CATEGORY',
  USER = 'USER',
  JOB = 'JOB',
  PERMISSION = 'PERMISSION',
  PROFILE = 'PROFILE',
  ARTICLE = 'ARTICLE',
  ROLE = 'ROLE',
  SKILL = 'SKILL',
  EDUCATION = 'EDUCATION',
  EXPERIENCE = 'EXPERIENCE',
  ADDRESS = 'ADDRESS',
}
